//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnsureThat.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnsureThat.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected an expression that evaluates to false..
        /// </summary>
        internal static string EnsureExtensions_IsFalse {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value &apos;{0}&apos; is not greater than limit &apos;{1}&apos;..
        /// </summary>
        internal static string EnsureExtensions_IsGt {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsGt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value &apos;{0}&apos; is not greater than or equal to limit &apos;{1}&apos;..
        /// </summary>
        internal static string EnsureExtensions_IsGte {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsGte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value &apos;{0}&apos; is &gt; max &apos;{1}&apos;..
        /// </summary>
        internal static string EnsureExtensions_IsInRange_ToHigh {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsInRange_ToHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value &apos;{0}&apos; is &lt; min &apos;{1}&apos;..
        /// </summary>
        internal static string EnsureExtensions_IsInRange_ToLow {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsInRange_ToLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value &apos;{0}&apos; is not lower than limit &apos;{1}&apos;..
        /// </summary>
        internal static string EnsureExtensions_IsLt {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsLt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value &apos;{0}&apos; is not lower than or equal to limit &apos;{1}&apos;..
        /// </summary>
        internal static string EnsureExtensions_IsLte {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsLte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty collection is not allowed..
        /// </summary>
        internal static string EnsureExtensions_IsNonEmptyCollection {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsNonEmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Guid is not allowed..
        /// </summary>
        internal static string EnsureExtensions_IsNonEmptyGuid {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsNonEmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can not be null..
        /// </summary>
        internal static string EnsureExtensions_IsNotNull {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string can&apos;t be null or empty..
        /// </summary>
        internal static string EnsureExtensions_IsNotNullOrEmpty {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string can&apos;t be left empty, null or consist of only whitespaces..
        /// </summary>
        internal static string EnsureExtensions_IsNotNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsNotNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The param is not of expected type: &apos;{0}&apos;..
        /// </summary>
        internal static string EnsureExtensions_IsOfType {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected an expression that evaluates to true..
        /// </summary>
        internal static string EnsureExtensions_IsTrue {
            get {
                return ResourceManager.GetString("EnsureExtensions_IsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No MemberExpression found in expression: &apos;{0}&apos;..
        /// </summary>
        internal static string ExpressionUtils_GetRightMostMember_NoMemberFound {
            get {
                return ResourceManager.GetString("ExpressionUtils_GetRightMostMember_NoMemberFound", resourceCulture);
            }
        }
    }
}
