stages:
- stage: Build
  jobs:
  - job: BuildTestPack
    displayName: 'Build, test & pack'
    timeoutInMinutes: 5
    cancelTimeoutInMinutes: 2
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Build Solution'
      inputs:
        command: build
        projects: 'src/*.sln'
        arguments: '-c $(BuildConfiguration) --no-incremental --nologo -p:TreatWarningsAsErrors=true -p:Version=$(SemVer) -p:InformationalVersion=$(CommitId)'

    - task: DotNetCoreCLI@2
      displayName: 'UnitTests .NetCoreApp3.1'
      inputs:
        command: test
        projects: 'src/**/UnitTests.csproj'
        arguments: '-c $(BuildConfiguration) -f netcoreapp3.1 --no-build'
        testRunTitle: 'UnitTests .NetCoreApp3.1'

    - task: DotNetCoreCLI@2
      displayName: 'UnitTests .Net5'
      inputs:
        command: test
        projects: 'src/**/UnitTests.csproj'
        arguments: '-c $(BuildConfiguration) -f net5.0 --no-build'
        testRunTitle: 'UnitTests .Net5'

    - task: DotNetCoreCLI@2
      displayName: 'Pack Nupkg'
      inputs:
        command: custom
        custom: pack
        projects: 'src/*.sln'
        arguments: '-c $(BuildConfiguration) --no-build -o $(Build.ArtifactStagingDirectory) -p:Version=$(SemVer) -p:InformationalVersion=$(CommitId)'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifacts'
      inputs:
        path: '$(Build.ArtifactStagingDirectory)'
        artifact: Artifacts
