stages:
- stage: Deploy
  condition: and (succeeded(), startsWith( variables['Build.SourceBranch'], 'refs/tags' ))
  dependsOn: Build
  jobs:
  - deployment: DeployArtifacts
    environment: 'Prod'
    displayName: 'Deploys artifacts'
    timeoutInMinutes: 10
    cancelTimeoutInMinutes: 2
    strategy: 
      runOnce:
        deploy:
          steps:
          - checkout: none
          - task: NuGetCommand@2
            displayName: 'Push Nupkg to NuGet'
            inputs:
              command: push
              nugetFeedType: external
              publishFeedCredentials: nuget_push
              verbosityPush: Normal
              packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg;!$(Pipeline.Workspace)/**/*.symbols.nupkg'
